#@baseurl = https://verified-bluesky-rpu7w3bv.fermyon.app
#@baseurl = https://verified-bluesky.germanywestcentral.cloudapp.azure.com
#@baseurl = https://verifiedbsky.net
@baseurl = http://localhost:3000

###
# get title, first and second levels 
GET {{baseurl}}/validate-mvp/

###
# get list and starter packs
GET {{baseurl}}/validate-mvp/Verified MVPs: AI Platform

###
# get list and starter packs
GET {{baseurl}}/validate-mvp/Verified MVPs

###
# validate
POST {{baseurl}}/validate-mvp
Content-Type: text/json

{
    "bskyHandle": "tobiasfenster.io",
    "verificationId": "2efc9bb2-6a8c-e711-811e-3863bb36edf8"
}

###
# validate in verify-only mode (using query parameter)
POST {{baseurl}}/validate-mvp?verify_only=true
Content-Type: text/json

{
    "bskyHandle": "tobiasfenster.io",
    "verificationId": "2efc9bb2-6a8c-e711-811e-3863bb36edf8"
}

###
# delete
DELETE {{baseurl}}/validate-rd/<pwd>
Content-Type: text/plain

{
    "bskyHandle": "tobiasfenster.io",
    "verificationId": "2efc9bb2-6a8c-e711-811e-3863bb36edf8"
}

###
# create lists and starter packs (done initially once per module)
PUT {{baseurl}}/validate-colorcloud/<pwd>

###
# get statistics
GET {{baseurl}}/stats/

###
# set labels (works only for MVPs and RDs atm!)
PUT {{baseurl}}/admin/<pwd>

{
    "Key": "mvp-2efc9bb2-6a8c-e711-811e-3863bb36edf8",
    "Value": "tobiasfenster.io"
}

###
# export k/v data
GET {{baseurl}}/admin/data/<pwd>

###
# import k/v data from another backend
POST {{baseurl}}/admin/data/<pwd>

"https://www.ars-solvendi.de/export.json"

###
# validate account
GET {{baseurl}}/weekly-validation/tobiasfenster.io/<pwd>

###
# test all
@testurl = {{baseurl}}/validate-

# CNCF Ambassador
POST {{testurl}}cncfamb
Content-Type: text/json

{
    "bskyHandle": "calummurray.bsky.social",
    "verificationId": "calum-murray"
}

###
# Cloud Technology Townhall Tallinn speaker
POST {{testurl}}cttt
Content-Type: text/json

{
    "bskyHandle": "katerinach.bsky.social",
    "verificationId": "Katerina Chernevskaya"
}

###
# ColorCloud speaker
POST {{testurl}}colorcloud
Content-Type: text/json

{
    "bskyHandle": "paulinekolde.info",
    "verificationId": "Pauline Kolde"
}

###
# DynamicsMinds speaker
POST {{testurl}}dynamicsminds
Content-Type: text/json

{
    "bskyHandle": "tobiasfenster.io",
    "verificationId": "Tobias Fenster"
}

###
# GitHub Star
POST {{testurl}}ghstar
Content-Type: text/json

{
    "bskyHandle": "eliostruyf.com",
    "verificationId": "estruyf"
}

###
# Java Champion
POST {{testurl}}javachamps
Content-Type: text/json

{
    "bskyHandle": "tomcools.be",
    "verificationId": "Tom Cools"
}

###
# Microsoft MVP
POST {{testurl}}mvp
Content-Type: text/json

{
    "bskyHandle": "ivarribas.bsky.social",
    "verificationId": "82ccb254-c755-ed11-9561-000d3a197333"
}

###
# Microsoft RD
POST {{testurl}}rd
Content-Type: text/json

{
    "bskyHandle": "fiddi.ch",
    "verificationId": "5e5388e5-2153-e511-810d-fc15b4285d7c"
}

###
# Oracle ACE
POST {{testurl}}oracleace
Content-Type: text/json

{
    "bskyHandle": "mthmulders.bsky.social",
    "verificationId": "mthmulders"
}

###
# AWS Hero
POST {{testurl}}awshero
Content-Type: text/json

{
    "bskyHandle": "eminalemdar.bsky.social",
    "verificationId": "emin-alemdar"
}

###
# IBM Champion
POST {{testurl}}ibmchamp
Content-Type: text/json

{
    "bskyHandle": "richard.fichtner.dev",
    "verificationId": "rfichtner"
}