POST http://localhost:3000/validate-rd
Content-Type: text/plain

{
    "bskyHandle": "tobiasfenster.io",
    "verificationId": "2efc9bb2-6a8c-e711-811e-3863bb36edf8"
}

###
POST http://localhost:3000/validate-mvp
Content-Type: application/json

{
    "bskyHandle": "a",
    "mvpId": "b"
}


###
POST http://localhost:3000/validate-mvp
Content-Type: application/json

{
    "bskyHandle": "kevchant.bsky.social",
    "verificationId": "5538c444-ef18-eb11-a813-000d3a8dfe0d"
}

###
PUT http://localhost:3000/validate-rd/

###
DELETE http://localhost:3000/admin/

###
GET http://localhost:3000/validate-mvp/

###
GET http://localhost:3000/validate-rd/

###
GET http://localhost:3000/validate-mvp/Verified MVPs: AI Platform

###
GET http://localhost:3000/validate-rd/Verified MVPs

###
GET https://mavenapi-prod.azurewebsites.net/api/mvp/UserProfiles/public/5538c444-ef18-eb11-a813-000d3a8dfe0d

###
GET https://mavenapi-prod.azurewebsites.net/api/mvp/UserProfiles/public/2efc9bb2-6a8c-e711-811e-3863bb36edf8