spin_manifest_version = 2

[application]
name = "verified-bluesky"
version = "0.17.1"
authors = ["tobiasfenster.io"]
description = "Backend and frontend for Bluesky account verification and storage"

[variables]
bsky_handle = { required = true }
bsky_password = { required = true }
bsky_did = { required = true }
bsky_labeler_did = { required = true }
admin_mode = { default = "false" }
kv_explorer_user = { required = true }
kv_explorer_password = { required = true }
verify_only = { default = "true" }
validation_base_url = { default = "https://verifiedbsky.net" }

[[trigger.http]]
route = "/admin/..."
component = "admin"

[component.admin]
source = "admin/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.admin.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
admin_mode = "{{ admin_mode }}"
verify_only = "{{ verify_only }}"
[component.admin.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "admin"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/admin/data/..."
component = "data"

[component.data]
source = "data/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
    "https://verifiedbsky.net",
    "https://www.ars-solvendi.de",
]
key_value_stores = ["default"]
[component.data.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
admin_mode = "{{ admin_mode }}"
verify_only = "{{ verify_only }}"
[component.data.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "data"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-mvp/..."
component = "validate-mvp"

[component.validate-mvp]
source = "validate-mvp/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://mavenapi-prod.azurewebsites.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-mvp.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-mvp.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-mvp"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-rd/..."
component = "validate-rd"

[component.validate-rd]
source = "validate-rd/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://mavenapi-prod.azurewebsites.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-rd.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-rd.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-rd"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "static", destination = "/" }]

[[trigger.http]]
component = "kv-explorer"
route = "/internal/kv-explorer/..."

[component.kv-explorer]
source = { url = "https://github.com/fermyon/spin-kv-explorer/releases/download/v0.10.0/spin-kv-explorer.wasm", digest = "sha256:65bc286f8315746d1beecd2430e178f539fa487ebf6520099daae09a35dbce1d" }
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
key_value_stores = ["default"]

[component.kv-explorer.variables]
kv_credentials = "{{ kv_explorer_user }}:{{ kv_explorer_password }}"

[[trigger.http]]
route = "/validate-dynamicsminds/..."
component = "validate-dynamicsminds"

[component.validate-dynamicsminds]
source = "validate-dynamicsminds/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://api.runevents.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-dynamicsminds.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-dynamicsminds.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-dynamicsminds"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-ghstar/..."
component = "validate-ghstar"

[component.validate-ghstar]
source = "validate-ghstar/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://stars.github.com",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-ghstar.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-ghstar.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-ghstar"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-javachamps/..."
component = "validate-javachamps"

[component.validate-javachamps]
source = "validate-javachamps/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://javachampions.org",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-javachamps.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-javachamps.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-javachamps"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-cncfamb/..."
component = "validate-cncfamb"

[component.validate-cncfamb]
source = "validate-cncfamb/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://www.cncf.io",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-cncfamb.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-cncfamb.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-cncfamb"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/stats/..."
component = "stats"

[component.stats]
source = "stats/main.wasm"
allowed_outbound_hosts = [
    "redis://redis-verified-bluesky.redis.cache.windows.net:6380",
    "rediss://redis-verified-bluesky.redis.cache.windows.net:6380"
]
key_value_stores = ["default"]
[component.stats.build]
command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
workdir = "stats"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-oracleace/..."
component = "validate-oracleace"

[component.validate-oracleace]
source = "validate-oracleace/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://apexadb.oracle.com",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-oracleace.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-oracleace.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-oracleace"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-cttt/..."
component = "validate-cttt"

[component.validate-cttt]
source = "validate-cttt/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
    "https://sessionize.com",
]
key_value_stores = ["default"]
[component.validate-cttt.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-cttt.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-cttt"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-colorcloud/..."
component = "validate-colorcloud"

[component.validate-colorcloud]
source = "validate-colorcloud/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
    "https://sessionize.com",
]
key_value_stores = ["default"]
[component.validate-colorcloud.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-colorcloud.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-colorcloud"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-awshero/..."
component = "validate-awshero"

[component.validate-awshero]
source = "validate-awshero/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
    "https://aws.amazon.com",
]
key_value_stores = ["default"]
[component.validate-awshero.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-awshero.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-awshero"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-ibmchamp/..."
component = "validate-ibmchamp"

[component.validate-ibmchamp]
source = "validate-ibmchamp/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
    "https://community.ibm.com",
]
key_value_stores = ["default"]
[component.validate-ibmchamp.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-ibmchamp.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-ibmchamp"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-nordicsummit/..."
component = "validate-nordicsummit"

[component.validate-nordicsummit]
source = "validate-nordicsummit/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
    "https://sessionize.com",
]
key_value_stores = ["default"]
[component.validate-nordicsummit.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
verify_only = "{{ verify_only }}"
[component.validate-nordicsummit.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-nordicsummit"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/weekly-validation/..."
component = "weekly-validation"

[component.weekly-validation]
source = "weekly-validation/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
    "https://verifiedbsky.net",
    "http://localhost:3000",
]
key_value_stores = ["default"]
[component.weekly-validation.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
admin_mode = "{{ admin_mode }}"
verify_only = "{{ verify_only }}"
validation_base_url = "{{ validation_base_url }}"
[component.weekly-validation.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "weekly-validation"
watch = ["**/*.go", "go.mod"]
