spin_manifest_version = 2

[application]
name = "verified-bluesky"
version = "0.4.2"
authors = ["tobiasfenster.io"]
description = "Backend and frontend for Bluesky account verification and storage"

[variables]
bsky_handle = { required = true }
bsky_password = { required = true }
bsky_did = { required = true }
bsky_labeler_did = { required = true }
admin_mode = { default = "false" }

[[trigger.http]]
route = "/admin/..."
component = "admin"

[component.admin]
source = "admin/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.admin.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
admin_mode = "{{ admin_mode }}"
[component.admin.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "admin"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-mvp/..."
component = "validate-mvp"

[component.validate-mvp]
source = "validate-mvp/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://mavenapi-prod.azurewebsites.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-mvp.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
[component.validate-mvp.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-mvp"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-rd/..."
component = "validate-rd"

[component.validate-rd]
source = "validate-rd/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://mavenapi-prod.azurewebsites.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-rd.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
[component.validate-rd.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-rd"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "static", destination = "/" }]
