spin_manifest_version = 2

[application]
name = "verified-bluesky"
version = "0.7.2"
authors = ["tobiasfenster.io"]
description = "Backend and frontend for Bluesky account verification and storage"

[variables]
bsky_handle = { required = true }
bsky_password = { required = true }
bsky_did = { required = true }
bsky_labeler_did = { required = true }
admin_mode = { default = "false" }
kv_explorer_user = { required = true }
kv_explorer_password = { required = true }

[[trigger.http]]
route = "/admin/..."
component = "admin"

[component.admin]
source = "admin/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.admin.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
admin_mode = "{{ admin_mode }}"
[component.admin.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "admin"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-mvp/..."
component = "validate-mvp"

[component.validate-mvp]
source = "validate-mvp/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://mavenapi-prod.azurewebsites.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-mvp.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
[component.validate-mvp.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-mvp"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-rd/..."
component = "validate-rd"

[component.validate-rd]
source = "validate-rd/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://mavenapi-prod.azurewebsites.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-rd.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
[component.validate-rd.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-rd"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "static", destination = "/" }]

[[trigger.http]]
component = "kv-explorer"
route = "/internal/kv-explorer/..."

[component.kv-explorer]
source = { url = "https://github.com/fermyon/spin-kv-explorer/releases/download/v0.10.0/spin-kv-explorer.wasm", digest = "sha256:65bc286f8315746d1beecd2430e178f539fa487ebf6520099daae09a35dbce1d" }
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
# add or remove stores you want to explore here
key_value_stores = ["default"]

[component.kv-explorer.variables]
kv_credentials = "{{ kv_explorer_user }}:{{ kv_explorer_password }}"

[[trigger.http]]
route = "/validate-dynamicsminds/..."
component = "validate-dynamicsminds"

[component.validate-dynamicsminds]
source = "validate-dynamicsminds/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://api.runevents.net",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-dynamicsminds.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
[component.validate-dynamicsminds.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-dynamicsminds"
watch = ["**/*.go", "go.mod"]

[[trigger.http]]
route = "/validate-ghstar/..."
component = "validate-ghstar"

[component.validate-ghstar]
source = "validate-ghstar/main.wasm"
allowed_outbound_hosts = [
    "https://bsky.social",
    "https://stars.github.com",
    "https://*.bsky.network",
]
key_value_stores = ["default"]
[component.validate-ghstar.variables]
bsky_handle = "{{ bsky_handle }}"
bsky_password = "{{ bsky_password }}"
bsky_did = "{{ bsky_did }}"
bsky_labeler_did = "{{ bsky_labeler_did }}"
[component.validate-ghstar.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "validate-ghstar"
watch = ["**/*.go", "go.mod"]
