spin_manifest_version = 2

[application]
name = "verified-bluesky"
version = "0.13.3"
authors = ["tobiasfenster.io"]
description = "Backend and frontend for Bluesky account verification and storage"

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "static", destination = "/" }]
