apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: verified-bluesky
spec:
  image: "verifiedbluesky.azurecr.io/verified-bluesky:v0.10.14"
  executor: containerd-shim-spin
  replicas: 1
  variables:
    - name: bsky_handle
      value: "verifiedbsky.net"
    - name: bsky_did
      value: "did:plc:px34esz3zqocesnhjoyllu7q"
    - name: bsky_labeler_did
      value: "did:plc:ar7c4by46qjdydhdevvrndac"
    - name: kv_explorer_user
      value: "tfenster"
    - name: verify_only
      value: "false"
    - name: admin_mode
      value: "false"
    - name: kv_explorer_password
      valueFrom:
        secretKeyRef:
          name: kv-explorer-password
          key: password
          optional: false
    - name: bsky_password
      valueFrom:
        secretKeyRef:
          name: bsky-password
          key: password
          optional: false
  runtimeConfig:
    loadFromSecret: verified-bluesky-runtime-config