name: "Continuous Deployment"
on:
  push:
    tags:
    - 'v*' 
env:
  GO_VERSION: "1.23.2"
  TINYGO_VERSION: "v0.34.0"
  SPIN_VERSION: ""
jobs:
  spin:
    runs-on: "ubuntu-latest"
    name: Build Spin App
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Install TinyGo
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: "${{ env.TINYGO_VERSION }}"
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          plugins: 
      - name: Build and push
        id: push
        uses: fermyon/actions/spin/push@v1
        with:
          registry: verifiedbluesky.azurecr.io
          registry_username: ${{ secrets.ACR_USERNAME }}
          registry_password: ${{ secrets.ACR_PASSWORD }}
          registry_reference: "verifiedbluesky.azurecr.io/verified-bluesky:${{ github.ref_name }}"
      - name: echo digest
        run: echo ${{ steps.push.outputs.digest }}
